version: "3.5"
services:
    web:
        container_name: ipresence_web
        image: nginx:latest
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/web
            - ./docker/nginx/site.conf:/etc/nginx/conf.d/site.conf
        networks:
        - ipresence
    php:
        container_name: ipresence_php
        build: ./docker/php
        volumes:
            - .:/var/www/web
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
        networks:
        - ipresence
    redis:
        container_name: ipresence_redis
        image: "redis:latest"
        command: redis-server --requirepass Li6sgcoWEzGlQrVbpaAS
        ports:
            - "127.0.0.1:6379:6379"
        networks:
            ipresence:
                aliases:
                    - local-redis

networks:
    ipresence: